import { createContext, useContext, useEffect, useMemo, useRef, useState, type KeyboardEvent, type ReactNode } from 'react'
import { APP_VERSION } from './app-info'
import { identityApi, identityConfigured, isSetupCodeRejected } from './identity-api'
import { canManageDevices, canManageEmployees, canRemoveDeviceAccess, canRenameDevices, clearTerminalSession, isValidDeviceName, isValidPinFormat, readDeviceToken, readTerminalSession, writeTerminalSession, type Employee, type EmployeeRole, type TerminalSession } from './identity'
import { assertConnectedBackendMutationAllowed, isConnectivityFailure } from './connection-safety'
import { initializeDevice, type DeviceStartupState } from './identity-initialization'
import { QRCodeSVG } from 'qrcode.react'
import { consumeSetupCode, enrollmentSetupUrl, formatEnrollmentCode, isCompleteEnrollmentCode, normalizeEnrollmentCode, shareOrCopySetup } from './enrollment-setup'
import { completeDeviceEnrollment } from './enrollment-completion'

type IdentityValue = { employee: Employee; sessionToken: string; lock: () => void; switchUser: () => void; manageEmployees: () => void; manageDevices: () => void }
const IdentityContext = createContext<IdentityValue | null>(null)
export const useActiveEmployee = () => { const value=useContext(IdentityContext); if(!value)throw new Error('Active employee context is unavailable.'); return value }

const deviceToken = () => readDeviceToken()
const identityLoadError = (fallback: string) => fallback

export function IdentityGate({ children }: { children: ReactNode }) {
  const [session,setSession]=useState<TerminalSession|null>(()=>readTerminalSession())
  const [startup,setStartup]=useState<DeviceStartupState>({status:'CHECKING'})
  const [startupAttempt,setStartupAttempt]=useState(0)
  const [recovering,setRecovering]=useState(false)
  const [selected,setSelected]=useState<Employee|null>(null)
  const [locked,setLocked]=useState(false)
  const [manage,setManage]=useState(false)
  const [devices,setDevices]=useState(false)
  useEffect(()=>{let current=true;setStartup({status:'CHECKING'});initializeDevice(window.localStorage,token=>identityApi.listActive(token)).then(result=>{if(current)setStartup(result)});return()=>{current=false}},[startupAttempt])
  const retryStartup=()=>{setRecovering(false);setStartupAttempt(value=>value+1)}
  const lock=()=>{clearTerminalSession();setLocked(true);setSelected(session?.employee??null);setSession(null)}
  const switchUser=()=>{clearTerminalSession();setLocked(false);setSelected(null);setSession(null)}
  if(startup.status==='CHECKING')return <BrandedStartup/>
  if(startup.status==='NEW_DEVICE'||recovering)return <DeviceSetup onContinue={retryStartup}/>
  if(startup.status==='ACCESS_REMOVED')return <IdentityStatus title="ACCESS REMOVED" detail="This device no longer has access to Blue Springs Bowl.\n\nAsk an Owner to add it again." action="TRY AGAIN" onAction={retryStartup} secondaryAction="I HAVE A SETUP CODE" onSecondaryAction={()=>setRecovering(true)}/>
  if(startup.status==='OFFLINE')return <IdentityStatus title="CONNECTION NEEDED" detail="Blue Springs Bowl couldn't be reached.\n\nCheck the internet connection, then try again." action="TRY AGAIN" onAction={retryStartup}/>
  if (!session) return <LoginScreen initialEmployees={startup.employees} selected={selected} locked={locked} onSelect={setSelected} onBack={()=>{setSelected(null);setLocked(false)}} onAuthenticated={value=>{writeTerminalSession(value);setSession(value);setLocked(false)}} />
  const value={employee:session.employee,sessionToken:session.token,lock,switchUser,manageEmployees:()=>setManage(true),manageDevices:()=>setDevices(true)}
  return <IdentityContext.Provider value={value}>{children}{manage&&<EmployeeManager session={session} close={()=>setManage(false)}/>}{devices&&<DeviceManager session={session} close={()=>setDevices(false)}/>}</IdentityContext.Provider>
}

export function ActiveEmployeeControl() {
  const identity=useActiveEmployee(); const [open,setOpen]=useState(false)
  return <div className="employee-control"><button onClick={()=>setOpen(!open)} aria-expanded={open}>{identity.employee.displayName} <span>▾</span></button>{open&&<div className="employee-menu">{canManageEmployees(identity.employee)&&<button onClick={()=>{setOpen(false);identity.manageEmployees()}}><MenuIcon kind="employees"/>Employees</button>}{canManageDevices(identity.employee)&&<button onClick={()=>{setOpen(false);identity.manageDevices()}}><MenuIcon kind="device"/>Center Devices</button>}<button onClick={identity.lock}><MenuIcon kind="lock"/>Lock</button><button onClick={identity.switchUser}><MenuIcon kind="switch"/>Switch User</button></div>}</div>
}

function MenuIcon({kind}:{kind:'employees'|'device'|'lock'|'switch'}) { return <svg className="employee-menu-icon" viewBox="0 0 24 24" aria-hidden="true">{kind==='employees'&&<><circle cx="9" cy="8" r="3" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M3.5 19c.4-3.3 2.3-5 5.5-5s5.1 1.7 5.5 5M16 5.5a2.6 2.6 0 0 1 0 5.1M16 14c2.7.1 4.2 1.6 4.5 4.5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></>}{kind==='device'&&<><rect x="6" y="3" width="12" height="18" rx="1.5" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M10 17h4" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></>}{kind==='lock'&&<><rect x="5" y="10" width="14" height="10" rx="1.5" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v2" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></>}{kind==='switch'&&<><path d="M4 7h12l-3-3M20 17H8l3 3M16 7l3 3M8 17l-3-3" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></>}</svg> }

function LoginScreen({initialEmployees,selected,locked,onSelect,onBack,onAuthenticated}:{initialEmployees:Employee[];selected:Employee|null;locked:boolean;onSelect:(employee:Employee)=>void;onBack:()=>void;onAuthenticated:(session:TerminalSession)=>void}) {
  const [employees,setEmployees]=useState<Employee[]>(initialEmployees); const [pin,setPin]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const submitting=useRef(false)
  useEffect(()=>{if(selected||employees.length)return;const token=deviceToken();if(!identityConfigured||!token){setError('Employee sign-in is unavailable.');return}setBusy(true);identityApi.listActive(token).then(setEmployees).catch(()=>setError(identityLoadError('Employee list is unavailable. Check the connection and try again.'))).finally(()=>setBusy(false))},[employees.length,selected])
  const enter=async(pinToVerify=pin)=>{if(submitting.current||!selected||!isValidPinFormat(pinToVerify))return setError('Enter your 4-digit PIN.');submitting.current=true;setBusy(true);setError('');try{onAuthenticated(await identityApi.verifyPin(deviceToken(),selected.id,pinToVerify))}catch{setPin('');setError("That PIN didn't work.")}finally{submitting.current=false;setBusy(false)}}
  const key=(value:string)=>{if(submitting.current)return;if(value==='clear')setPin('');else if(value==='back')setPin(current=>current.slice(0,-1));else if(pin.length<4){const next=pin+value;setPin(next);if(next.length===4)void enter(next)}setError('')}
  const keyboard=(event:KeyboardEvent<HTMLElement>)=>{if(!selected||submitting.current)return;if(/^\d$/.test(event.key)){event.preventDefault();key(event.key)}else if(event.key==='Backspace'){event.preventDefault();key('back')}else if(event.key==='Escape'){event.preventDefault();key('clear')}else if(event.key==='Enter'){event.preventDefault();void enter()}}
  return <main className="identity-screen"><section className="identity-panel" onKeyDown={keyboard} tabIndex={selected?0:undefined} autoFocus={Boolean(selected)}><img src="/blue-springs-bowl-logo.png" alt="Blue Springs Bowl"/><p className="identity-product">OPEN PLAY BOOK <span>v{APP_VERSION}</span></p><h1>{locked?'WELCOME BACK':"WHO'S WORKING?"}</h1>{!selected?<><div className="employee-grid">{employees.map(employee=><button key={employee.id} onClick={()=>onSelect(employee)}>{employee.displayName}<small>{employee.role}</small></button>)}</div>{busy&&<p>Loading employees…</p>}</>:<><button className="selected-employee" onClick={onBack} disabled={busy}>‹ {selected.displayName}</button><div className="pin-dots" aria-label={busy?'Verifying PIN':`${pin.length} PIN digits entered`} aria-live="polite">{[0,1,2,3].map(index=><i className={index<pin.length?'filled':''} key={index}/>)}</div><div className="pin-keypad" aria-label="PIN keypad">{['1','2','3','4','5','6','7','8','9','clear','0','back'].map(value=><button key={value} disabled={busy} onClick={()=>key(value)} aria-label={value==='back'?'Backspace':value==='clear'?'Clear':value}>{value==='back'?'⌫':value==='clear'?'CLEAR':value}</button>)}</div><button className="pin-enter" disabled={busy||pin.length!==4} onClick={()=>void enter()}>ENTER</button></>}{error&&<p className="identity-error" role="alert">{error}<br/>Please try again.</p>}</section></main>
}

function EmployeeManager({session,close}:{session:TerminalSession;close:()=>void}) {
  const [employees,setEmployees]=useState<Employee[]>([]);const [editing,setEditing]=useState<Employee|null|undefined>(undefined);const [name,setName]=useState('');const [role,setRole]=useState<EmployeeRole>('EMPLOYEE');const [active,setActive]=useState(true);const [pin,setPin]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(true)
  const load=()=>identityApi.listAll(session.token).then(setEmployees).catch(e=>setError(e instanceof Error?e.message:'Unable to load employees.')).finally(()=>setBusy(false));useEffect(()=>{void load()},[])
  const edit=(employee:Employee|null)=>{setEditing(employee);setName(employee?.displayName??'');setRole(employee?.role??'EMPLOYEE');setActive(employee?.active??true);setPin('');setError('')}
  const save=async()=>{if(!name.trim())return setError('Display name is required.');if((!editing||pin)&&!isValidPinFormat(pin))return setError('A new PIN must be exactly 4 digits.');setBusy(true);try{assertConnectedBackendMutationAllowed();await identityApi.saveEmployee(session.token,{id:editing?.id,displayName:name.trim(),role,active,pin:pin||undefined});setEditing(undefined);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save employee.')}finally{setBusy(false)}}
  const sorted=useMemo(()=>[...employees].sort((a,b)=>a.displayName.localeCompare(b.displayName)),[employees])
  return <div className="overlay" onMouseDown={close}><section className="sheet employee-admin" role="dialog" aria-modal="true" aria-label={editing===null?'Add Employee':'Employees'} onMouseDown={e=>e.stopPropagation()}><header><h2>{editing===null?'Add Employee':'Employees'}</h2><button aria-label="Close dialog" onClick={close}>×</button></header>{editing!==undefined?<div className="employee-form"><label>Employee Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value as EmployeeRole)}><option>EMPLOYEE</option><option>MANAGER</option><option>OWNER</option></select></label><label className="active-check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active employee</label><label>{editing?'New PIN (leave blank to keep current)':'4-digit PIN'}<input type="password" inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))}/></label>{error&&<p className="identity-error">{error}</p>}<div className="employee-form-actions"><button className="primary" disabled={busy} onClick={save}>Save Employee</button><button className="employee-form-cancel" onClick={()=>setEditing(undefined)}>Cancel</button></div></div>:<><div className="employee-list">{busy&&<p>Loading…</p>}{sorted.map(employee=><article className="employee-row" key={employee.id}><div><b>{employee.displayName}</b><small>{employee.role} · {employee.active?'ACTIVE':'INACTIVE'}</small></div><button onClick={()=>edit(employee)}>Edit / Reset PIN</button></article>)}</div>{error&&<p className="identity-error">{error}</p>}<div className="employee-admin-actions"><button className="primary" onClick={()=>edit(null)}>+ Add Employee</button></div></>}</section></div>
}

function DeviceSetup({onContinue}:{onContinue:()=>void}) {
  const setupCode=typeof window==='undefined'?'':consumeSetupCode(window.location.href,url=>window.history.replaceState(window.history.state,'',url))
  const [step,setStep]=useState<'INTRO'|'CODE'|'READY'|'CODE_REJECTED'|'OFFLINE'>(()=>isCompleteEnrollmentCode(setupCode)?'CODE':'INTRO')
  const [code,setCode]=useState(setupCode);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const redeem=async()=>{if(!isCompleteEnrollmentCode(code))return setError('Enter the complete setup code.');setBusy(true);setError('');try{const result=await identityApi.redeemDeviceEnrollment(normalizeEnrollmentCode(code));completeDeviceEnrollment(result.device_token,{storage:window.localStorage,clearSetupCode:()=>setCode(''),replaceUrl:url=>window.history.replaceState(window.history.state,'',url)});setStep('READY')}catch(e){if(isConnectivityFailure(e))setStep('OFFLINE');else if(isSetupCodeRejected(e))setStep('CODE_REJECTED');else setError('Setup could not be completed. Please try again.')}finally{setBusy(false)}}
  if(step==='INTRO')return <IdentityStatus title="SET UP THIS DEVICE" detail={["This computer hasn't been set up for Blue Springs Bowl yet.","You'll only need to do this once."]} action="I HAVE A SETUP CODE" onAction={()=>setStep('CODE')} help="Need a code? On a Blue Springs Bowl device that's already working, sign in and choose Center Devices → Add Device."/>
  if(step==='READY')return <IdentityStatus title="THIS DEVICE IS READY" detail="" action="CONTINUE" onAction={onContinue}/>
  if(step==='CODE_REJECTED')return <IdentityStatus title="THAT CODE NO LONGER WORKS" detail={["Setup codes can only be used once and expire quickly.","Ask an Owner or Manager for a new code."]} action="ENTER A NEW CODE" onAction={()=>{setCode('');setStep('CODE')}}/>
  if(step==='OFFLINE')return <IdentityStatus title="INTERNET CONNECTION NEEDED" detail={["This device must connect to the internet the first time it is set up.","Check the connection, then try again."]} action="TRY AGAIN" onAction={()=>setStep('CODE')}/>
  return <main className="identity-screen"><section className="identity-panel"><img src="/blue-springs-bowl-logo.png" alt="Blue Springs Bowl"/><p className="identity-product">OPEN PLAY BOOK</p><h1>ENTER SETUP CODE</h1><p>Ask an Owner or Manager for the setup code.</p><label>Setup Code<input autoFocus value={formatEnrollmentCode(code)} onChange={e=>setCode(normalizeEnrollmentCode(e.target.value))} placeholder="XXXXXXXX-XXXXXXXX"/></label><button className="pin-enter" disabled={busy||!isCompleteEnrollmentCode(code)} onClick={redeem}>FINISH SETUP</button>{error&&<p className="identity-error">{error}</p>}</section></main>
}

function DeviceManager({session,close}:{session:TerminalSession;close:()=>void}) {
  const [devices,setDevices]=useState<{id:string;display_name:string;active:boolean;last_seen_at:string|null;is_current:boolean}[]>([]);const [adding,setAdding]=useState(false);const [name,setName]=useState('');const [editing,setEditing]=useState<string|null>(null);const [removedOpen,setRemovedOpen]=useState(false);const [setup,setSetup]=useState<{code:string;expires_at:string;device_name:string}|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('')
  const load=()=>identityApi.listDevices(session.token).then(setDevices).catch(()=>setError('Unable to load Center Devices. Check the connection and try again.'));useEffect(()=>{void load()},[])
  const create=async()=>{if(!isValidDeviceName(name))return setError('Device Name is required and must be 80 characters or fewer.');try{assertConnectedBackendMutationAllowed();setSetup(await identityApi.createDeviceEnrollment(session.token,name.trim()));setName('');setNotice('');setError('')}catch{setError('Unable to create a setup code. Check the connection and try again.')}}
  const copy=async()=>{if(!setup)return;try{if(!navigator.clipboard)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(setup.code);setNotice('Code copied.')}catch{setNotice('Unable to copy. Copy the code shown above.')}}
  const share=async()=>{if(!setup)return;try{const result=await shareOrCopySetup(setup.code,window.location.origin,{share:typeof navigator.share==='function'?{share:navigator.share.bind(navigator)}:undefined,clipboard:navigator.clipboard?{writeText:navigator.clipboard.writeText.bind(navigator.clipboard)}:undefined});setNotice(result==='shared'?'Code shared.':result==='copied'?'Setup link copied.':result==='unavailable'?'Sharing is unavailable. Copy the code shown above.':'Sharing cancelled.')}catch{setNotice('Unable to share. Copy the code shown above.')}}
  const remove=async(id:string)=>{try{assertConnectedBackendMutationAllowed();await identityApi.setDeviceActive(session.token,id,false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to remove access.')}}
  const rename=async()=>{if(!editing)return;if(!isValidDeviceName(name))return setError('Device Name is required and must be 80 characters or fewer.');try{assertConnectedBackendMutationAllowed();await identityApi.renameDevice(session.token,editing,name.trim());setEditing(null);setName('');setError('');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to rename device.')}}
  const setupUrl=setup?enrollmentSetupUrl(setup.code,window.location.origin):'';const canShare=typeof navigator.share==='function'||Boolean(navigator.clipboard);const active=devices.filter(d=>d.active);const removed=devices.filter(d=>!d.active)
  const row=(d:typeof devices[number])=><article className="employee-row device-row" key={d.id}><div><b>{d.display_name}</b>{d.is_current&&<span className="this-device">THIS DEVICE</span>}<small>{d.active?'WORKING':'ACCESS REMOVED'}{d.last_seen_at?` · Last Used ${new Date(d.last_seen_at).toLocaleString()}`:''}</small></div><div className="device-actions">{d.active&&canRenameDevices(session.employee)&&<button onClick={()=>{setEditing(d.id);setName(d.display_name);setError('')}}>Rename Device</button>}{d.active&&canRemoveDeviceAccess(session.employee)&&<button onClick={()=>remove(d.id)}>Remove Access</button>}</div></article>
  const content=setup?<section className="device-enrollment"><p><b>{setup.device_name}</b></p><h2>{setup.code}</h2><p>Enter this code on the new device.</p><p className="muted">Expires {new Date(setup.expires_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}. It can only be used once.</p><div className="enrollment-qr"><QRCodeSVG value={setupUrl} size={192} level="M" includeMargin/><small>Scan with the new device</small></div><div className="enrollment-actions"><button className="secondary" onClick={copy}>Copy Code</button>{canShare&&<button className="primary" onClick={share}>Share Code</button>}</div>{notice&&<p className="muted" role="status">{notice}</p>}<button className="primary full" onClick={()=>{setSetup(null);setAdding(false);void load()}}>Done</button></section>:adding?<div className="employee-form"><label>Device Name<input autoFocus maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Front Desk"/></label><button className="primary full" onClick={create}>Create Setup Code</button><button className="secondary full" onClick={()=>setAdding(false)}>Cancel</button></div>:editing?<div className="employee-form"><label>Device Name<input autoFocus maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary full" onClick={rename}>Save</button><button className="secondary full" onClick={()=>{setEditing(null);setName('')}}>Cancel</button></div>:<><button className="primary full" onClick={()=>setAdding(true)}>+ Add Device</button><div className="employee-list">{active.map(row)}</div>{removed.length>0&&<section className="removed-devices"><button className="removed-toggle" aria-expanded={removedOpen} onClick={()=>setRemovedOpen(value=>!value)}>Access Removed ({removed.length}) <span>⌄</span></button>{removedOpen&&<div className="employee-list">{removed.map(row)}</div>}</section>}</>
  return <div className="overlay" onMouseDown={close}><section className="sheet employee-admin" role="dialog" aria-modal="true" aria-label="Center Devices" onMouseDown={e=>e.stopPropagation()}><header><h2>Center Devices</h2><button aria-label="Close dialog" onClick={close}>×</button></header>{content}{error&&<p className="identity-error">{error}</p>}</section></div>
}

function BrandedStartup(){return <main className="identity-screen"><section className="identity-panel startup-panel"><img src="/blue-springs-bowl-logo.png" alt="Blue Springs Bowl"/><p className="identity-product">OPEN PLAY BOOK</p><h1>OPEN PLAY BOOK</h1><p className="identity-message">Getting things ready…</p></section></main>}
function IdentityStatus({title,detail,action,onAction,secondaryAction,onSecondaryAction,help}:{title:string;detail:string|string[];action?:string;onAction?:()=>void;secondaryAction?:string;onSecondaryAction?:()=>void;help?:string}) {
  return <main className="identity-screen"><section className="identity-panel operational-status"><img src="/blue-springs-bowl-logo.png" alt="Blue Springs Bowl"/><p className="identity-product">OPEN PLAY BOOK</p><h1>{title}</h1>{detail&&<div className="identity-message">{(Array.isArray(detail)?detail:[detail]).map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div>}{action&&<button className="pin-enter" onClick={onAction}>{action}</button>}{secondaryAction&&<button className="secondary identity-secondary" onClick={onSecondaryAction}>{secondaryAction}</button>}{help&&<p className="identity-help">{help}</p>}</section></main>
}
