import { activeAssignments, assignmentsFor, calculatePricing, defaultChargeCents, defaults, iso, makeId, type ActivityEvent, type AppState, type LaneConditionKind, type League, type Session, type SessionType, type Settings } from './domain'
export const STORAGE_KEY = 'bsb-counter:v1'
export const migrateState = (value: unknown): AppState => { if (value && typeof value === 'object') { const parsed = value as Partial<AppState>; if (parsed.schemaVersion === 1 && parsed.settings && parsed.sessions && parsed.laneAssignments && parsed.leagues && parsed.laneConditions) { const baseline=defaults().settings; const settings={...baseline,...parsed.settings,openBowlingGracePeriodMinutes:parsed.settings.openBowlingGracePeriodMinutes??baseline.openBowlingGracePeriodMinutes,openBowlingMinimumChargeCents:parsed.settings.openBowlingMinimumChargeCents??baseline.openBowlingMinimumChargeCents}; const sessions=Object.fromEntries(Object.entries(parsed.sessions).map(([id,session])=>session.type==='OPEN_BOWLING'?[id,{...session,pricing:{...session.pricing,gracePeriodMinutes:session.pricing.gracePeriodMinutes??baseline.openBowlingGracePeriodMinutes,minimumChargeCents:session.pricing.minimumChargeCents??baseline.openBowlingMinimumChargeCents}}]:session.type==='PARTY'?[id,{...session,partyAmountCents:session.partyAmountCents??0}]:[id,session])); return {...parsed,settings,sessions} as AppState } } return defaults() }
export const loadState = (): AppState => { try { const saved = localStorage.getItem(STORAGE_KEY); return saved ? migrateState(JSON.parse(saved)) : defaults() } catch { return defaults() } }
export const saveState = (state: AppState) => localStorage.setItem(STORAGE_KEY, JSON.stringify(state))
const withEvent = (state: AppState, event: Omit<ActivityEvent, 'id'>): AppState => ({ ...state, activity: [{ ...event, id: makeId() }, ...state.activity].slice(0, 2000) })
const nightFor = (state: AppState, now: string) => { if (state.currentNightId) return [state, state.currentNightId] as const; const night = { id: makeId(), businessDate: new Intl.DateTimeFormat('en-CA', { timeZone: state.settings.timezone }).format(new Date(now)), openedAt: now, closedAt: null, status: 'OPEN' as const }; return [{ ...state, currentNightId: night.id, nights: { ...state.nights, [night.id]: night } }, night.id] as const }
export const openNight = (state: AppState, now = iso()): AppState => nightFor(state, now)[0]
export type StartInput = { type: SessionType; lanes: number[]; partyName?: string; notes?: string; bowlerCount?: number; shoeCount?: number; partyAmountCents?: number; leagueId?: string; designation?: 'PRE' | 'POST'; teamDescription?: string; downOverrides?: number[] }
export const startSession = (state: AppState, input: StartInput, now = iso()): AppState => {
  const duplicate = input.lanes.some(lane => activeAssignments(state).some(a => a.laneNumber === lane)); if (!input.lanes.length || duplicate) throw new Error('Select one or more available lanes.')
  const [withNight, nightId] = nightFor(state, now); const base = { id: makeId(), nightId, type: input.type, status: 'ACTIVE' as const, startedAt: now, endedAt: null, createdAt: now, updatedAt: now, notes: input.notes?.trim() || null }
  let session: Session
  if (input.type === 'OPEN_BOWLING') session = { ...base, type: input.type, partyName: input.partyName?.trim() || null, bowlerCount: input.bowlerCount ?? 0, shoeCount: input.shoeCount ?? 0, pricing: { laneRateCentsPerHour: withNight.settings.openBowlingLaneRateCents, shoeRateCents: withNight.settings.shoeRentalRateCents, gracePeriodMinutes: withNight.settings.openBowlingGracePeriodMinutes, minimumChargeCents: withNight.settings.openBowlingMinimumChargeCents, calculatedTotalCents: null, roundedTotalCents: null, chargedTotalCents: null, adjustmentNote: null } }
  else if (input.type === 'PRE_POST') { const league = withNight.leagues[input.leagueId ?? '']; if (!league || !league.active || league.deleted) throw new Error('Select an active league/night.'); session = { ...base, type: input.type, leagueId: league.id, leagueNameSnapshot: league.name, designation: input.designation ?? 'PRE', teamDescription: input.teamDescription?.trim() || null, bowlerCount: input.bowlerCount ?? 0 } }
  else session = { ...base, type: input.type, partyName: input.partyName?.trim() || 'Party', bowlerCount: input.bowlerCount ?? 0, partyAmountCents: Math.max(0, input.partyAmountCents ?? 0) }
  const assignments = Object.fromEntries(input.lanes.map(lane => { const assignment = { id: makeId(), sessionId: session.id, laneNumber: lane, startedAt: now, billableStartedAt: null, endedAt: null, endReason: null, downOverrideConfirmed: input.downOverrides?.includes(lane) ?? false }; return [assignment.id, assignment] }))
  return withEvent({ ...withNight, sessions: { ...withNight.sessions, [session.id]: session }, laneAssignments: { ...withNight.laneAssignments, ...assignments } }, { nightId, occurredAt: now, type: 'SESSION_STARTED', sessionId: session.id, laneNumbers: input.lanes, summary: `Started ${input.type.replace('_', ' ').toLowerCase()}` })
}
export const addLane = (state: AppState, sessionId: string, lane: number, downOverride: boolean, now = iso()) => { const session = state.sessions[sessionId]; if (!session || session.status !== 'ACTIVE') throw new Error('This session is not active.'); if (occupiedByOther(state, lane, sessionId)) throw new Error(`Lane ${lane} is already in use.`); const assignment = { id: makeId(), sessionId, laneNumber: lane, startedAt: now, billableStartedAt: null, endedAt: null, endReason: null, downOverrideConfirmed: downOverride }; return withEvent({ ...state, laneAssignments: { ...state.laneAssignments, [assignment.id]: assignment } }, { nightId: session.nightId, occurredAt: now, type: 'LANE_ADDED', sessionId, laneNumbers: [lane], summary: `Added lane ${lane}` }) }
export const startBillingNow = (state: AppState, sessionId: string, now = iso()) => { const session=state.sessions[sessionId]; if(!session||session.type!=='OPEN_BOWLING'||session.status!=='ACTIVE') throw new Error('This open-bowling session is not active.'); const laneAssignments={...state.laneAssignments}; const started=activeAssignments(state,sessionId).filter(a=>!a.billableStartedAt&&new Date(a.startedAt).getTime()+session.pricing.gracePeriodMinutes*60_000>new Date(now).getTime()); started.forEach(a=>laneAssignments[a.id]={...a,billableStartedAt:now}); return started.length?withEvent({...state,laneAssignments},{nightId:session.nightId,occurredAt:now,type:'BILLING_STARTED',sessionId,laneNumbers:started.map(a=>a.laneNumber),summary:'Started billing now'}):state }
const occupiedByOther = (state: AppState, lane: number, sessionId: string) => activeAssignments(state).some(a => a.laneNumber === lane && a.sessionId !== sessionId)
export const releaseLane = (state: AppState, sessionId: string, lane: number, now = iso()) => { const assignment = activeAssignments(state, sessionId).find(a => a.laneNumber === lane); const session = state.sessions[sessionId]; if (!assignment || !session) throw new Error('Lane is not assigned to this active session.'); const laneAssignments = { ...state.laneAssignments, [assignment.id]: { ...assignment, endedAt: now, endReason: 'RELEASED' as const } }; return withEvent({ ...state, laneAssignments }, { nightId: session.nightId, occurredAt: now, type: 'LANE_RELEASED', sessionId, laneNumbers: [lane], summary: `Released lane ${lane}` }) }
export const endSession = (state: AppState, sessionId: string, now = iso()) => { const session = state.sessions[sessionId]; if (!session || session.status !== 'ACTIVE') throw new Error('This session is not active.'); const lanes = activeAssignments(state, sessionId); const laneAssignments = { ...state.laneAssignments }; lanes.forEach(a => { laneAssignments[a.id] = { ...a, endedAt: now, endReason: 'SESSION_ENDED' } }); let updated: Session = { ...session, status: 'AWAITING_CLOSE', endedAt: now, updatedAt: now }; if (updated.type === 'OPEN_BOWLING') { const pricing = calculatePricing({ ...state, laneAssignments }, updated, now); updated = { ...updated, pricing: { ...updated.pricing, ...pricing } } } return withEvent({ ...state, sessions: { ...state.sessions, [sessionId]: updated }, laneAssignments }, { nightId: session.nightId, occurredAt: now, type: 'SESSION_ENDED', sessionId, laneNumbers: lanes.map(a => a.laneNumber), summary: 'Ended session' }) }
export const closeSession = (state: AppState, sessionId: string, chargedTotalCents?: number, adjustmentNote?: string, now = iso()) => { const session = state.sessions[sessionId]; const paymentPending = session?.type === 'OPEN_BOWLING' && session.pricing.chargedTotalCents === null; if (!session || (session.status !== 'AWAITING_CLOSE' && !paymentPending)) throw new Error('End the session before closing it.'); let updated: Session = { ...session, status: 'COMPLETED', updatedAt: now }; if (updated.type === 'OPEN_BOWLING') updated = { ...updated, pricing: { ...updated.pricing, chargedTotalCents: chargedTotalCents ?? defaultChargeCents(updated.pricing.roundedTotalCents ?? 0, updated.pricing.minimumChargeCents), adjustmentNote: adjustmentNote?.trim() || null } }; return withEvent({ ...state, sessions: { ...state.sessions, [sessionId]: updated } }, { nightId: session.nightId, occurredAt: now, type: 'SESSION_CLOSED', sessionId, laneNumbers: assignmentsFor(state, sessionId).map(a => a.laneNumber), summary: 'Closed session' }) }
export const reopenSession = (state: AppState, sessionId: string, now = iso()) => { const session = state.sessions[sessionId]; if (!session || session.status === 'ACTIVE') throw new Error('This session cannot be reopened.'); const restore = assignmentsFor(state, sessionId).filter(a => a.endReason === 'SESSION_ENDED'); const conflicts = restore.filter(a => activeAssignments(state).some(other => other.laneNumber === a.laneNumber && other.sessionId !== sessionId)).map(a => a.laneNumber); if (conflicts.length) throw new Error(`Cannot reopen: lane${conflicts.length > 1 ? 's' : ''} ${conflicts.join(', ')} ${conflicts.length > 1 ? 'are' : 'is'} now in use.`); const laneAssignments = { ...state.laneAssignments }; restore.forEach(a => laneAssignments[a.id] = { ...a, endedAt: null, endReason: null }); let updated: Session = { ...session, status: 'ACTIVE', endedAt: null, updatedAt: now }; if (updated.type === 'OPEN_BOWLING') updated = { ...updated, pricing: { ...updated.pricing, calculatedTotalCents: null, roundedTotalCents: null, chargedTotalCents: null, adjustmentNote: null } }; return withEvent({ ...state, sessions: { ...state.sessions, [sessionId]: updated }, laneAssignments }, { nightId: session.nightId, occurredAt: now, type: 'SESSION_REOPENED', sessionId, laneNumbers: restore.map(a => a.laneNumber), summary: 'Reopened session' }) }
export const updateCondition = (state: AppState, lane: number, condition: LaneConditionKind, note: string, now = iso()) => ({ ...state, laneConditions: { ...state.laneConditions, [lane]: { laneNumber: lane, condition, note: note.trim() || null, updatedAt: now } } })
export const addLeague = (state: AppState, name: string) => { const trimmed=name.trim(); if(!trimmed) throw new Error('League name is required.'); const league={id:makeId(),name:trimmed,active:true,sortOrder:Object.keys(state.leagues).length}; return {...state,leagues:{...state.leagues,[league.id]:league}} }
export const updateLeague = (state: AppState, id: string, patch: Partial<League>) => { const league=state.leagues[id]; if(!league) throw new Error('League option not found.'); return {...state,leagues:{...state.leagues,[id]:{...league,...patch,name:patch.name?.trim()||league.name}}} }
export const moveLeague = (state: AppState, id: string, direction: -1|1) => { const ordered=Object.values(state.leagues).sort((a,b)=>a.sortOrder-b.sortOrder); const index=ordered.findIndex(l=>l.id===id), swap=index+direction; if(index<0||swap<0||swap>=ordered.length)return state; const leagues={...state.leagues,[ordered[index].id]:{...ordered[index],sortOrder:ordered[swap].sortOrder},[ordered[swap].id]:{...ordered[swap],sortOrder:ordered[index].sortOrder}};return {...state,leagues} }
export const saveSettings = (state: AppState, settings: Settings, leagues: Record<string, League>) => ({ ...state, settings, leagues })
export const editActiveSession = (state: AppState, sessionId: string, patch: Partial<Session>, now = iso()) => { const session = state.sessions[sessionId]; if (!session || session.status !== 'ACTIVE') throw new Error('Only active sessions can be edited.'); const startedAt = patch.startedAt ?? session.startedAt; if (Number.isNaN(new Date(startedAt).getTime()) || new Date(startedAt) > new Date(now)) throw new Error('Start time cannot be in the future.'); const initial = activeAssignments(state, sessionId).filter(a => a.startedAt === session.startedAt); if (initial.some(a => new Date(startedAt) > new Date(a.endedAt ?? now))) throw new Error('Start time creates an impossible lane interval.'); const updated = { ...session, ...patch, startedAt, updatedAt: now } as Session; const laneAssignments = { ...state.laneAssignments }; initial.forEach(a => laneAssignments[a.id] = { ...a, startedAt }); return { ...state, sessions: { ...state.sessions, [sessionId]: updated }, laneAssignments } }
export const endNight = (state: AppState, now = iso()) => { const night = state.currentNightId && state.nights[state.currentNightId]; if (!night) throw new Error('There is no open night.'); const outstanding = Object.values(state.sessions).filter(s => s.nightId === night.id && (s.status !== 'COMPLETED' || (s.type === 'OPEN_BOWLING' && s.pricing.chargedTotalCents === null))); if (outstanding.length) throw new Error(`${outstanding.length} session${outstanding.length === 1 ? '' : 's'} still need${outstanding.length === 1 ? 's' : ''} resolution.`); return { ...state, currentNightId: null, nights: { ...state.nights, [night.id]: { ...night, closedAt: now, status: 'ARCHIVED' as const } } } }
