import { describe, expect, it } from 'vitest'
import { activeAssignments, calculatePricing, completedPartyRevenueCents, defaultChargeCents, defaults, fromLocalDateTimeInput, nightRevenueSummary, operationalLaneHours, operationalSessions, toLocalDateTimeInput } from './domain'
import { addLane, closeSession, editActiveSession, endNight, endSession, migrateState, moveLane, openNight, reinstateSession, reopenSession, releaseLane, saveSettings, startBillingNow, startSession, voidSession } from './store'

const at = (value: string) => new Date(`2026-09-20T${value}Z`).toISOString()
const startOpen = (lanes = [3]) => startSession(defaults(), { type: 'OPEN_BOWLING', lanes, partyName: 'Smith', shoeCount: 4 }, at('19:45:00'))

describe('open bowling pricing', () => {
  it('applies each lane minimum before shoes and tax, retaining exact cents', () => { let state=startSession(defaults(),{type:'OPEN_BOWLING',lanes:[1,2],shoeCount:3},at('19:00:00'));const session=Object.values(state.sessions)[0];state=endSession(state,session.id,at('19:06:00'));const ended=state.sessions[session.id];if(ended.type==='OPEN_BOWLING'){const price=calculatePricing(state,ended,at('19:06:00'));expect(price.bowlingSubtotalCents).toBe(1000);expect(price.shoeSubtotalCents).toBe(900);expect(price.taxCents).toBe(166);expect(price.calculatedTotalCents).toBe(2066);expect(price.roundedTotalCents).toBe(2066);expect(defaultChargeCents(price.calculatedTotalCents)).toBe(2066)}})
  it('aggregates differently-timed lane assignments before rounding cents', () => {
    let state = startOpen(); const session = Object.values(state.sessions)[0]
    state = addLane(state, session.id, 4, false, at('20:17:00'))
    state = endSession(state, session.id, at('21:00:00'))
    const ended = state.sessions[session.id]; expect(ended.type).toBe('OPEN_BOWLING')
    if (ended.type === 'OPEN_BOWLING') { const price = calculatePricing(state, ended, at('21:00:00')); expect(price.laneTimeCents).toBe(4500); expect(price.shoeCents).toBe(1200); expect(price.taxCents).toBe(497); expect(price.calculatedTotalCents).toBe(6197); expect(price.roundedTotalCents).toBe(6197) }
  })
  it('does not whole-dollar round new taxed customer totals', () => { let state = startOpen(); const session = Object.values(state.sessions)[0]; state = endSession(state, session.id, at('20:58:48')); const ended = state.sessions[session.id]; if (ended.type === 'OPEN_BOWLING') { expect(ended.pricing.calculatedTotalCents).toBe(4422); expect(ended.pricing.roundedTotalCents).toBe(4422); state=closeSession(state,session.id,undefined,'',at('20:59:00')); const paid=state.sessions[session.id]; if(paid.type==='OPEN_BOWLING'){expect(paid.pricing.chargedTotalCents).toBe(4422);expect(paid.checkedOutAt).toBe(at('20:59:00'))} } })
  it('does not bill lane time during each assignment grace period', () => { let state = startOpen([1]); const session = Object.values(state.sessions)[0]; state = endSession(state, session.id, at('19:49:59')); const ended = state.sessions[session.id]; if (ended.type === 'OPEN_BOWLING') { const price=calculatePricing(state, ended, at('19:49:59')); expect(price.laneTimeCents).toBe(0); expect(price.shoeCents).toBe(1200) } })
  it('gives a later-added lane its own grace period', () => { let state=startOpen([1]); const session=Object.values(state.sessions)[0]; state=addLane(state,session.id,2,false,at('20:00:00')); const active=state.sessions[session.id]; if(active.type==='OPEN_BOWLING'){const price=calculatePricing(state,active,at('20:04:00')); expect(price.laneTimeCents).toBe(583)}})
  it('does not apply the lane minimum before a lane ever becomes billable and retains manual overrides', () => { let state=startSession(defaults(),{type:'OPEN_BOWLING',lanes:[1],shoeCount:0},at('19:45:00')); const session=Object.values(state.sessions)[0]; state=endSession(state,session.id,at('19:46:00')); const ended=state.sessions[session.id]; if(ended.type==='OPEN_BOWLING') expect(defaultChargeCents(ended.pricing.roundedTotalCents??0)).toBe(0); state=closeSession(state,session.id,undefined,'',at('19:47:00')); const paid=state.sessions[session.id]; if(paid.type==='OPEN_BOWLING') expect(paid.pricing.chargedTotalCents).toBe(0); state=reopenSession(state,session.id,at('19:48:00')); state=endSession(state,session.id,at('19:49:00')); state=closeSession(state,session.id,0,'manual comp',at('19:50:00')); const overridden=state.sessions[session.id]; if(overridden.type==='OPEN_BOWLING') expect(overridden.pricing.chargedTotalCents).toBe(0) })
  it('snapshots configured grace and lane minimum rules for new sessions', () => { let state=defaults(); state=saveSettings(state,{...state.settings,openBowlingGracePeriodMinutes:10,openBowlingMinimumChargeCents:700},state.leagues); state=startSession(state,{type:'OPEN_BOWLING',lanes:[1],shoeCount:0},at('19:45:00')); const session=Object.values(state.sessions)[0]; if(session.type==='OPEN_BOWLING'){expect(calculatePricing(state,session,at('19:54:59')).laneTimeCents).toBe(0);expect(session.pricing.minimumChargeCents).toBe(700)}state=endSession(state,session.id,at('19:46:00'));state=closeSession(state,session.id,undefined,'',at('19:47:00'));const paid=state.sessions[session.id];if(paid.type==='OPEN_BOWLING')expect(paid.pricing.chargedTotalCents).toBe(0) })
  it('does not rewrite historical session pricing when settings later change', () => { let state=startSession(defaults(),{type:'OPEN_BOWLING',lanes:[1]},at('19:45:00'));const session=Object.values(state.sessions)[0];state=saveSettings(state,{...state.settings,openBowlingLaneRateCents:4000,openBowlingGracePeriodMinutes:0,openBowlingMinimumChargeCents:900},state.leagues);const original=state.sessions[session.id];if(original.type==='OPEN_BOWLING'){expect(original.pricing.laneRateCentsPerHour).toBe(2500);expect(original.pricing.gracePeriodMinutes).toBe(5);expect(original.pricing.minimumChargeCents).toBe(500)}})
  it('starts billing now without billing unused grace and gives each billable lane its own minimum', () => { let state=startSession(defaults(),{type:'OPEN_BOWLING',lanes:[1,2],shoeCount:0},at('19:45:00'));const session=Object.values(state.sessions)[0];state=startBillingNow(state,session.id,at('19:47:00'));state=addLane(state,session.id,3,false,at('19:48:00'));const active=state.sessions[session.id];const assignments=Object.values(state.laneAssignments);expect(assignments.filter(a=>a.laneNumber!==3).every(a=>a.billableStartedAt===at('19:47:00'))).toBe(true);expect(assignments.find(a=>a.laneNumber===3)?.billableStartedAt).toBeNull();if(active.type==='OPEN_BOWLING'){const price=calculatePricing(state,active,at('19:52:00'));expect(price.laneTimeCents).toBe(1000)} })
  it('starts billing only for the lane selected by its session-console card', () => { let state=startSession(defaults(),{type:'OPEN_BOWLING',lanes:[1,2],shoeCount:0},at('19:45:00'));const session=Object.values(state.sessions)[0];state=startBillingNow(state,session.id,at('19:47:00'),2);const lanes=Object.values(state.laneAssignments);expect(lanes.find(a=>a.laneNumber===1)?.billableStartedAt).toBeNull();expect(lanes.find(a=>a.laneNumber===2)?.billableStartedAt).toBe(at('19:47:00')) })
  it('removes an unbilled lane during grace without creating a minimum and leaves the session active', () => { let state=startSession(defaults(),{type:'OPEN_BOWLING',lanes:[1,2],shoeCount:0},at('19:00:00'));const session=Object.values(state.sessions)[0];state=releaseLane(state,session.id,2,at('19:02:00'));const active=state.sessions[session.id];if(active.type==='OPEN_BOWLING'){const price=calculatePricing(state,active,at('19:02:00'));expect(price.laneCharges.find(l=>l.laneNumbers.includes(2))?.chargeCents).toBe(0)}expect(active.status).toBe('ACTIVE');expect(activeAssignments(state).some(a=>a.laneNumber===2)).toBe(false);expect(Object.values(state.laneAssignments).find(a=>a.laneNumber===2)?.endedAt).toBeTruthy() })
  it('removes one billable lane while preserving its accrued minimum and the other lane', () => { let state=startSession(defaults(),{type:'OPEN_BOWLING',lanes:[1,2],shoeCount:0},at('19:00:00'));const session=Object.values(state.sessions)[0];state=releaseLane(state,session.id,2,at('19:06:00'));const active=state.sessions[session.id];if(active.type==='OPEN_BOWLING'){const price=calculatePricing(state,active,at('19:06:00'));expect(price.laneCharges.find(l=>l.laneNumbers.includes(2))?.chargeCents).toBe(500);expect(activeAssignments(state,session.id).map(a=>a.laneNumber)).toEqual([1])} })
})
describe('lane assignment lifecycle', () => {
  it('moves a physical lane without creating a second minimum or overlapping charge', () => { let state=startSession(defaults(),{type:'OPEN_BOWLING',lanes:[5],shoeCount:0},at('19:00:00'));const session=Object.values(state.sessions)[0];state=moveLane(state,session.id,5,6,false,at('19:40:00'));state=endSession(state,session.id,at('20:00:00'));const ended=state.sessions[session.id];if(ended.type==='OPEN_BOWLING'){const price=calculatePricing(state,ended,at('20:00:00'));expect(price.laneCharges).toHaveLength(1);expect(price.laneCharges[0].laneNumbers).toEqual([5,6]);expect(price.laneTimeCents).toBe(2292)}expect(Object.values(state.laneAssignments).find(a=>a.laneNumber===5)?.endReason).toBe('MOVED') })
  it('adds and releases individual lanes without changing other lanes', () => { let state = startOpen([1]); const session = Object.values(state.sessions)[0]; state = addLane(state, session.id, 7, false, at('20:00:00')); state = releaseLane(state, session.id, 1, at('20:10:00')); const assignments = Object.values(state.laneAssignments); expect(assignments.find(a=>a.laneNumber===1)?.endReason).toBe('RELEASED'); expect(assignments.find(a=>a.laneNumber===7)?.endedAt).toBeNull() })
  it('reopen restores session-ended lanes but not intentionally released lanes', () => { let state = startOpen([1,2]); const session = Object.values(state.sessions)[0]; state = releaseLane(state, session.id, 1, at('20:00:00')); state = endSession(state, session.id, at('20:30:00')); state = closeSession(state, session.id, 5000, '', at('20:31:00')); state = reopenSession(state, session.id, at('20:32:00')); const assignments = Object.values(state.laneAssignments); expect(assignments.find(a=>a.laneNumber===1)?.endedAt).toBeTruthy(); expect(assignments.find(a=>a.laneNumber===2)?.endedAt).toBeNull(); expect(state.sessions[session.id]).toMatchObject({status:'ACTIVE',reopenedAt:at('20:32:00')}) })
  it('blocks a reopen when its formerly-ended lane has been reassigned', () => { let state = startOpen([3]); const original = Object.values(state.sessions)[0]; state = endSession(state, original.id, at('20:00:00')); state = closeSession(state, original.id, 2500, '', at('20:01:00')); state = startSession(state, { type:'PARTY', lanes:[3], partyName:'Birthday' }, at('20:02:00')); expect(() => reopenSession(state, original.id, at('20:03:00'))).toThrow('lane 3 is now in use') })
})
describe('party amounts', () => {
  it('persists the fixed amount through lane changes and completion', () => { let state=startSession(defaults(),{type:'PARTY',lanes:[3],partyName:'Birthday',partyAmountCents:15000},at('19:00:00'));const session=Object.values(state.sessions)[0];state=addLane(state,session.id,4,false,at('19:10:00'));state=releaseLane(state,session.id,3,at('19:20:00'));state=endSession(state,session.id,at('20:00:00'));state=closeSession(state,session.id,undefined,'',at('20:01:00'));const completed=state.sessions[session.id];if(completed.type==='PARTY')expect(completed.partyAmountCents).toBe(15000);expect(completedPartyRevenueCents(state,completed.nightId)).toBe(15000) })
  it('allows the active fixed amount to be corrected', () => { let state=startSession(defaults(),{type:'PARTY',lanes:[3],partyAmountCents:10000},at('19:00:00'));const session=Object.values(state.sessions)[0];state=editActiveSession(state,session.id,{partyAmountCents:17500},at('19:05:00'));const edited=state.sessions[session.id];if(edited.type==='PARTY')expect(edited.partyAmountCents).toBe(17500) })
})
describe('nightly accounting', () => {
  it('counts completed transaction amounts once and keeps shoes as an informational component', () => { let state=defaults();const makeOpen=(calculated:number,rounded:number,charged:number,shoes:number)=>{state=startSession(state,{type:'OPEN_BOWLING',lanes:[Object.keys(state.sessions).length+1],shoeCount:shoes},at('19:00:00'));const session=Object.values(state.sessions).at(-1)!;if(session.type==='OPEN_BOWLING')state={...state,sessions:{...state.sessions,[session.id]:{...session,status:'COMPLETED',pricing:{...session.pricing,calculatedTotalCents:calculated,roundedTotalCents:rounded,chargedTotalCents:charged}}}};return session.nightId};const nightId=makeOpen(3650,3700,3700,2);makeOpen(1000,1000,1500,0);makeOpen(6000,6000,5000,0);makeOpen(100,100,500,0);state=startSession(state,{type:'PARTY',lanes:[6,7],partyName:'Birthday',partyAmountCents:15000},at('19:00:00'));const party=Object.values(state.sessions).at(-1)!;state={...state,sessions:{...state.sessions,[party.id]:{...party,status:'COMPLETED'}}};state=startSession(state,{type:'PRE_POST',lanes:[8],leagueId:Object.values(state.leagues)[0].id},at('19:00:00'));const pre=Object.values(state.sessions).at(-1)!;state={...state,sessions:{...state.sessions,[pre.id]:{...pre,status:'COMPLETED'}}};const revenue=nightRevenueSummary(state,nightId);expect(revenue.calculatedOpenBowlingCents).toBe(10750);expect(revenue.openBowlingCollectedCents).toBe(10700);expect(revenue.shoeRentalCount).toBe(2);expect(revenue.shoeComponentCents).toBe(600);expect(revenue.partyCollectedCents).toBe(15000);expect(revenue.totalCollectedCents).toBe(25700);expect(revenue.openBowlingAdjustmentCents).toBe(-50) })
})
describe('persistence migration', () => {
  it('recovers a fresh safe state when persisted data is invalid', () => { const state = migrateState({ schemaVersion: 99 }); expect(state.schemaVersion).toBe(1); expect(Object.keys(state.laneConditions)).toHaveLength(12) })
  it('retains a valid version-one state', () => { const source = defaults(); expect(migrateState(source)).toStrictEqual(source) })
  it('adds pricing/timing defaults for legacy saved sessions and settings', () => { const source=defaults(); const legacy={...source,settings:{...source.settings,openBowlingGracePeriodMinutes:undefined,openBowlingMinimumChargeCents:undefined},sessions:{legacy:{id:'legacy',nightId:'night',type:'OPEN_BOWLING' as const,status:'COMPLETED' as const,startedAt:at('19:00:00'),endedAt:at('20:00:00'),createdAt:at('19:00:00'),updatedAt:at('20:00:00'),notes:null,partyName:null,bowlerCount:0,shoeCount:0,pricing:{laneRateCentsPerHour:2500,shoeRateCents:300,calculatedTotalCents:0,roundedTotalCents:0,chargedTotalCents:500,adjustmentNote:null}}}};const migrated=migrateState(legacy);const session=migrated.sessions.legacy;if(session.type==='OPEN_BOWLING'){expect(session.pricing.gracePeriodMinutes).toBe(5);expect(session.pricing.minimumChargeCents).toBe(500)}expect(migrated.settings.openBowlingGracePeriodMinutes).toBe(5) })
  it('treats a legacy Party without an amount as zero', () => { const source=defaults();const legacy={...source,sessions:{party:{id:'party',nightId:'night',type:'PARTY' as const,status:'COMPLETED' as const,startedAt:at('19:00:00'),endedAt:at('20:00:00'),createdAt:at('19:00:00'),updatedAt:at('20:00:00'),notes:null,partyName:'Legacy',bowlerCount:0}}};const migrated=migrateState(legacy);const party=migrated.sessions.party;if(party.type==='PARTY')expect(party.partyAmountCents).toBe(0);expect(completedPartyRevenueCents(migrated,'night')).toBe(0) })
  it('preserves a soft-deleted league for historical Pre/Post references', () => { let state=defaults();const league=Object.values(state.leagues)[0];state=startSession(state,{type:'PRE_POST',lanes:[2],leagueId:league.id,teamDescription:'Historical'},at('19:00:00'));state=saveSettings(state,state.settings,{...state.leagues,[league.id]:{...league,deleted:true,active:false}});const session=Object.values(state.sessions)[0];if(session.type==='PRE_POST')expect(session.leagueNameSnapshot).toBe(league.name);expect(state.leagues[league.id].deleted).toBe(true);expect(()=>startSession(state,{type:'PRE_POST',lanes:[3],leagueId:league.id},at('20:00:00'))).toThrow('active league') })
})
describe('start-time corrections', () => {
  it('updates initial lanes but preserves later lane timing and recalculates price', () => { let state = startOpen([1]); const session = Object.values(state.sessions)[0]; state = addLane(state, session.id, 2, false, at('20:00:00')); state = editActiveSession(state, session.id, { startedAt: at('19:30:00') }, at('21:00:00')); const lanes = Object.values(state.laneAssignments); expect(lanes.find(a=>a.laneNumber===1)?.startedAt).toBe(at('19:30:00')); expect(lanes.find(a=>a.laneNumber===2)?.startedAt).toBe(at('20:00:00')); const edited = state.sessions[session.id]; if (edited.type === 'OPEN_BOWLING') expect(calculatePricing(state, edited, at('21:00:00')).laneTimeCents).toBe(5834) })
  it('rejects future corrected start times', () => { const state = startOpen(); const session = Object.values(state.sessions)[0]; expect(() => editActiveSession(state, session.id, { startedAt: at('22:00:00') }, at('21:00:00'))).toThrow('future') })
})
describe('local datetime boundaries', () => {
  it('round trips a persisted UTC instant through the local datetime input without drift', () => { const utc='2026-09-20T06:46:00.000Z'; expect(fromLocalDateTimeInput(toLocalDateTimeInput(utc))).toBe(utc) })
})
describe('pending payment recovery', () => {
  it('accepts payment for a legacy completed open-bowling session with no charged total', () => { let state=startOpen([2]); const session=Object.values(state.sessions)[0]; state=endSession(state,session.id,at('20:00:00')); const ended=state.sessions[session.id]; state={...state,sessions:{...state.sessions,[session.id]:{...ended,status:'COMPLETED'}}}; state=closeSession(state,session.id,2500,'counter correction',at('20:01:00')); const paid=state.sessions[session.id]; expect(paid.status).toBe('COMPLETED'); if(paid.type==='OPEN_BOWLING') expect(paid.pricing.chargedTotalCents).toBe(2500) })
  it('keeps a cent-based pending payment recoverable and supports a cent override', () => { let state=startSession(defaults(),{type:'OPEN_BOWLING',lanes:[2],shoeCount:1},at('19:00:00')); const session=Object.values(state.sessions)[0]; state=endSession(state,session.id,at('19:06:00')); const pending=state.sessions[session.id]; expect(pending.status).toBe('AWAITING_CLOSE'); if(pending.type==='OPEN_BOWLING')expect(pending.pricing.calculatedTotalCents).toBe(870); state=closeSession(state,session.id,865,'five-cent courtesy',at('19:07:00')); const paid=state.sessions[session.id]; if(paid.type==='OPEN_BOWLING'){expect(paid.pricing.chargedTotalCents).toBe(865);expect((paid.pricing.chargedTotalCents??0)-(paid.pricing.calculatedTotalCents??0)).toBe(-5)} })
})
describe('closed-night lane initiation', () => {
  it('opens a new night before the preselected-lane start path', () => { let state=startOpen([7]); const session=Object.values(state.sessions)[0]; state=endSession(state,session.id,at('20:00:00')); state=closeSession(state,session.id,2500,'',at('20:01:00')); state=endNight(state,at('20:02:00')); expect(state.currentNightId).toBeNull(); state=openNight(state,at('20:03:00')); expect(state.currentNightId).toBeTruthy(); state=startSession(state,{type:'PARTY',lanes:[7],partyName:'Test'},at('20:03:01')); expect(Object.values(state.laneAssignments).some(a=>a.laneNumber===7&&!a.endedAt)).toBe(true) })
})

describe('session void reporting semantics', () => {
  const completedOpen=()=>{let state=startSession(defaults(),{type:'OPEN_BOWLING',lanes:[1],bowlerCount:3,shoeCount:2},at('19:00:00'));const session=Object.values(state.sessions)[0];state=endSession(state,session.id,at('20:00:00'));state=closeSession(state,session.id,3000,'',at('20:01:00'));return {state,sessionId:session.id,nightId:session.nightId}}
  it('rejects active sessions and blank notes',()=>{const state=startOpen();const session=Object.values(state.sessions)[0];expect(()=>voidSession(state,session.id,'OTHER','valid reason')).toThrow('End the session');const done=completedOpen();expect(()=>voidSession(done.state,done.sessionId,'OTHER','   ')).toThrow('meaningful')})
  it('preserves history and excludes voided Open Bowling revenue, groups, bowlers, shoes, and lane-hours',()=>{const {state,sessionId,nightId}=completedOpen();const priorEvents=state.activity.length;const voided=voidSession(state,sessionId,'TRAINING_TEST','George learning lane moves',at('20:02:00'));expect(voided.activity).toHaveLength(priorEvents+1);expect(voided.activity.some(event=>event.type==='PAYMENT_COMPLETED')).toBe(true);expect(voided.sessions[sessionId].status).toBe('VOIDED');expect(nightRevenueSummary(voided,nightId).totalCollectedCents).toBe(0);expect(operationalSessions(voided,nightId)).toHaveLength(0);expect(operationalLaneHours(voided,nightId)).toBe(0)})
  it('excludes voided Party and Pre/Post counts, revenue, and lane-hours',()=>{let state=defaults();state=startSession(state,{type:'PARTY',lanes:[3,4],partyName:'Test',partyAmountCents:15000,bowlerCount:8},at('19:00:00'));const party=Object.values(state.sessions)[0];state=endSession(state,party.id,at('20:00:00'));state=closeSession(state,party.id,undefined,'',at('20:01:00'));state=voidSession(state,party.id,'ENTERED_BY_MISTAKE','duplicate reservation',at('20:02:00'));state=startSession(state,{type:'PRE_POST',lanes:[7],leagueId:Object.values(state.leagues)[0].id,bowlerCount:4},at('20:03:00'));const pre=Object.values(state.sessions).at(-1)!;state=endSession(state,pre.id,at('20:30:00'));state=closeSession(state,pre.id,undefined,'',at('20:31:00'));state=voidSession(state,pre.id,'OTHER','wrong league selected',at('20:32:00'));expect(completedPartyRevenueCents(state,party.nightId)).toBe(0);expect(operationalSessions(state,party.nightId).filter(s=>s.type==='PARTY'||s.type==='PRE_POST')).toHaveLength(0);expect(operationalLaneHours(state,party.nightId)).toBe(0)})
  it('reinstates reporting inclusion and retains both immutable transition events',()=>{const {state,sessionId,nightId}=completedOpen();const voided=voidSession(state,sessionId,'DUPLICATE','duplicate entry',at('20:02:00'));const restored=reinstateSession(voided,sessionId,'voided wrong record',at('20:03:00'));expect(restored.sessions[sessionId].status).toBe('COMPLETED');expect(nightRevenueSummary(restored,nightId).totalCollectedCents).toBe(3000);expect(restored.activity.filter(event=>event.type==='SESSION_VOIDED')).toHaveLength(1);expect(restored.activity.filter(event=>event.type==='SESSION_REINSTATED')).toHaveLength(1)})
  it('records self-contained payment and Pre/Post completion activity',()=>{const open=completedOpen().state;const payment=open.activity.find(event=>event.type==='PAYMENT_COMPLETED')!;expect(payment.summary).toBe('Payment Complete · Open Bowling');expect(payment.details).toMatchObject({sessionType:'OPEN_BOWLING',laneHistory:[1],amountPaidCents:3000});const base=defaults();let pre=startSession(base,{type:'PRE_POST',lanes:[7,8],leagueId:Object.values(base.leagues)[0].id,designation:'POST'},at('19:00:00'));const session=Object.values(pre.sessions)[0];pre=endSession(pre,session.id,at('20:00:00'));pre=closeSession(pre,session.id,undefined,'',at('20:01:00'));expect(pre.activity[0].summary).toBe('Ended Post-Bowl');expect(pre.activity[0].laneNumbers).toEqual([7,8])})
})

describe('close-night unresolved-session safety', () => {
  const openSession=()=>{const state=startSession(defaults(),{type:'OPEN_BOWLING',lanes:[1],bowlerCount:2,shoeCount:1},at('19:00:00'));const session=Object.values(state.sessions)[0];return {state,session}}
  const completedSession=()=>{let {state}=openSession();const session=Object.values(state.sessions)[0];state=endSession(state,session.id,at('20:00:00'));state=closeSession(state,session.id,2500,'',at('20:01:00'));return {state,session:state.sessions[session.id]}}

  it('blocks ACTIVE non-void sessions',()=>{const {state}=openSession();expect(()=>endNight(state,at('21:00:00'))).toThrow('1 session still needs resolution')})
  it('blocks AWAITING_CLOSE non-void sessions',()=>{let {state}=openSession();const session=Object.values(state.sessions)[0];state=endSession(state,session.id,at('20:00:00'));expect(()=>endNight(state,at('21:00:00'))).toThrow('1 session still needs resolution')})
  it('allows COMPLETED sessions and closes when all non-void sessions are resolved',()=>{const {state}=completedSession();expect(endNight(state,at('21:00:00')).currentNightId).toBeNull()})
  it.each(['ACTIVE','AWAITING_CLOSE'] as const)('does not let a VOIDED session with pre-void %s block close',preVoidStatus=>{const {state,session}=openSession();const voided={...session,status:'VOIDED' as const,preVoidStatus,voidedAt:at('20:00:00')};const fixture={...state,sessions:{...state.sessions,[session.id]:voided}} as unknown as typeof state;expect(endNight(fixture,at('21:00:00')).currentNightId).toBeNull()})
  it('allows multiple voided sessions to close without weakening non-void checks',()=>{const first=openSession();const a=first.session;let state={...first.state,sessions:{...first.state.sessions,[a.id]:{...a,status:'VOIDED' as const,preVoidStatus:'ACTIVE' as const,voidedAt:at('19:30:00')}}} as unknown as typeof first.state;state=startSession(state,{type:'PARTY',lanes:[2],partyName:'Test'},at('19:31:00'));const b=Object.values(state.sessions).find(s=>s.id!==a.id)!;state=endSession(state,b.id,at('19:45:00'));state=voidSession(state,b.id,'OTHER','duplicate party',at('19:46:00'));expect(endNight(state,at('21:00:00')).currentNightId).toBeNull()})
  it('blocks a reinstated unresolved session again',()=>{let {state}=openSession();const session=Object.values(state.sessions)[0];state=endSession(state,session.id,at('20:00:00'));state=voidSession(state,session.id,'OTHER','entered by mistake',at('20:01:00'));state=reinstateSession(state,session.id,'restore correct entry',at('20:02:00'));expect(state.sessions[session.id].status).toBe('AWAITING_CLOSE');expect(()=>endNight(state,at('21:00:00'))).toThrow('1 session still needs resolution')})
  it('keeps voided sessions excluded from closeout totals and metrics',()=>{const {state,session}=completedSession();const nightId=session.nightId;const voided=voidSession(state,session.id,'TRAINING_TEST','training entry',at('20:02:00'));expect(nightRevenueSummary(voided,nightId).totalCollectedCents).toBe(0);expect(operationalSessions(voided,nightId)).toHaveLength(0);expect(operationalLaneHours(voided,nightId)).toBe(0);expect(endNight(voided,at('21:00:00')).currentNightId).toBeNull()})
})
